/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
import java.io.{ByteArrayOutputStream, PrintWriter}

import scala.sys.process._

class ScalaReactJS {
  private val REACT_STDIO_PATH = "/react-stdio-3.4.7"
  private val PROCESS_BUILDER = Process("npm info react-stdio")

  private val npmInfoTask = PROCESS_BUILDER.run

  def someLibraryMethod(): Boolean = true

  def runShellCommand(cmd: Seq[String]): (Int, String, String) = {
    val stdoutStream = new ByteArrayOutputStream
    val stderrStream = new ByteArrayOutputStream
    val stdoutWriter = new PrintWriter(stdoutStream)
    val stderrWriter = new PrintWriter(stderrStream)
    val exitValue = cmd.!(ProcessLogger(stdoutWriter.println, stderrWriter.println))
    stdoutWriter.close()
    stderrWriter.close()
    (exitValue, stdoutStream.toString, stderrStream.toString)
  }


  val npmInfo = npmInfoTask.exitValue

  val relativeDirectory = (runShellCommand(Seq("pwd")))


}
