/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
import java.io.{ByteArrayOutputStream, PrintWriter}

import scala.sys.process._

class ScalaReactJS {
  private val REACT_STDIO_PATH = "/react-stdio-3.4.7"

  def runShellCommand(cmd: Seq[String]): (Int, String, String) = {
    val stdoutStream = new ByteArrayOutputStream
    val stderrStream = new ByteArrayOutputStream
    val stdoutWriter = new PrintWriter(stdoutStream)
    val stderrWriter = new PrintWriter(stderrStream)
    val exitValue = cmd.!(ProcessLogger(stdoutWriter.println, stderrWriter.println))
    stdoutWriter.close()
    stderrWriter.close()
    (exitValue, stdoutStream.toString, stderrStream.toString)
  }

  val relativeDirectory = (runShellCommand(Seq("pwd")))._2
  val npmInfo = runShellCommand(Seq("npm", "info", "react-stdio"))._1

  def renderReactComponent(component: String, props: String): (String) = {

    val input = "{\"component\":\"./Dinosaur.js\",\"props\":{\"message\":\"hello\"}}"

    val p = runShellCommand(Seq("echo", input, "|", "react-stdio"))
    p.toString()
  }

}
