/** This Scala Testsuite was generated by the Gradle 'init' task.
 */
import org.scalatest.FunSuite
import org.junit.runner.RunWith
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class LibrarySuite extends FunSuite {
  def isEmpty(sOpt: Option[String]) = sOpt.forall(_.trim.isEmpty)

  test("verifies react-stdio npm package is available via npm info") {
    def library = new ScalaReactJS()
    val expected = library.npmInfo.toString()
    assert(!isEmpty(Some(expected)))
  }

  test("returns the file path of the library") {
    def library = new ScalaReactJS()
    val expected = library.relativeDirectory.toString()
    assert(!isEmpty(Some(expected)))
  }
}
